# 设置环境
language: bash
services:
  - docker

# 设置环境变量
env:
  - builder=muilt-arch                  # 多架构构建器的名字

# 提权
sudo: required

# 安装构建的依赖
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -                                    # 添加GPG Key
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"   # 添加PPA源地址
install:
  - sudo apt-get update                                                                                             # 更新源
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce                                          # 安装Docker CE
  - sudo apt-get -y install qemu-user                                                                               # 安装QEMU多架构模拟器
  - docker version                                                                                                  # 检查docker版本
  - docker buildx version                                                                                           # 验证buildx是否已启用

# 设置构建命令
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin   # 登录到Docker Hub
  - docker run --privileged --rm tonistiigi/binfmt --install all                    # 开启binfmt_misc多架构支持
  - docker buildx create --name "$builder"                                          # 创建由docker-container驱动的多架构构建器
  - docker buildx use "$builder"                                                    # 将默认构建器切换为多架构构建器
  - docker buildx inspect "$builder" --bootstrap                                    # 检查当前的构建器实例并确保其已启动
  - docker buildx ls                                                                # 查看构建器详情
script:
  - /usr/bin/bash build_redis_image.sh    # 运行镜像构建脚本
