# Version: 0.2
#
# 由于没有安装apt-utils，出现以下提示信息：
#   debconf: delaying package configuration, since apt-utils is not installed
# 目前看不必在意

ARG base_image_name
ARG base_image_tag
FROM ${base_image_name}:${base_image_tag}
MAINTAINER yj1516268@outlook.com
ENV TZ Asia/Shanghai
WORKDIR /usr/mabo/
COPY ./dockerfile/resource/script/*.sh ./dockerfile/resource/requirements_base-python.txt ./
RUN sed -i "s/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list \
    # 安装必要的软件包
    && apt-get update \
    && apt-get install -y curl freetds-dev libffi-dev build-essential git \
    # 设置时区
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && printf $TZ >/etc/timezone \
    # 修改pip源
    && /bin/bash ./configure_pip.sh \
    # 安装python包
    && pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --upgrade -r ./requirements_base-python.txt \
    && pip install --no-cache-dir --upgrade git+https://github.com/YHYJ/simplecannet \
    # 清理系统
    && apt-get purge -y manpages build-essential \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -r ./*.txt /var/lib/apt/lists/*
