# Version: 0.2
#
# `apk del`会导致出现警告信息：
#   WARNING: Ignoring APKINDEX.XXXXXX.tar.gz: No such file or directory
# 不必在意

ARG base_image_name
ARG base_image_tag
FROM ${base_image_name}:${base_image_tag}
ENV TZ Asia/Shanghai
WORKDIR /usr/mabo/
COPY ./dockerfile/resource/script/*.sh ./dockerfile/resource/requirements_base-python.txt ./
RUN printf "http://mirrors.ustc.edu.cn/alpine/v3.11/main\nhttp://mirrors.ustc.edu.cn/alpine/v3.11/community" >/etc/apk/repositories \
    # 安装必要的软件包
    && apk add --no-cache tzdata curl bash libstdc++ libc6-compat freetds-dev git \
    # 安装虚拟软件包.build-deps
    && apk add --no-cache --virtual .build-deps gcc g++ musl-dev openssl-dev libffi libffi-dev make \
    # 设置时区
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && printf $TZ >/etc/timezone \
    # 修改pip源
    && /bin/bash ./configure_pip.sh \
    # 安装python包
    && pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --upgrade -r ./requirements_base-python.txt \
    && pip install --no-cache-dir --upgrade https://files.pythonhosted.org/packages/4c/2b/eddbfc56076fae8deccca274a5c70a9eb1e0b334da0a33f894a420d0fe93/pycryptodome-3.9.8.tar.gz \
    && pip install --no-cache-dir --upgrade git+https://github.com/YHYJ/simplecannet \
    # 清理系统
    && apk del .build-deps \
    && rm -r ./*.sh ./*.txt /root/.cache
