# Version: 0.2

ARG base_image_name
ARG base_image_tag
FROM ${base_image_name}:${base_image_tag}
ENV TZ Asia/Shanghai
COPY ./dockerfile/resource/confile/redis.conf /etc/redis/
CMD redis-server /etc/redis/redis.conf
