name: Docker image

on:
  push:
    branches: [ redis_latest ]

jobs:
  multi-arch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile/Dockerfile_redis_latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          build-args: |
            base_image_name=redis
            base_image_tag=6.0-alpine
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/redis:latest
          push: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
